### ISSUE TITLE
List Property Use Case 

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#14]
Relates #6 (BE)

### Tasks 
- [ ] Use Case: Create a Property Listing from DTO
- [ ] Controller: API endpoint for creating a listing 
- [ ] Entity: Property Listing
- [ ] Schema: Property Listing
- [ ] DTO with format shown below

| Name | Type | Rules |
| ------------- | ------------- | ------------- |
| Property ID  | string  | required, uuid, belongs to user, has appropriate access type | 
| User ID   | string  | required, uuid, is existing user | 
| Available Date |  date  | required | 
| Monthly Rate |  number  | required, positive number, integer | 

### Test Cases 
- [ ] cannot list a property that does not exist 
- [ ] cannot list a property that you do not "own" or "manage"
- [ ] must list a property with available date and a monthly rate 
- [ ] returns 200 on success

**Comment by vincent-h-lee** [comment]
Completion of test cases blocked by #26
