### ISSUE TITLE
Create organizations and add members to them 

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#17]
### Tasks

- [ ] Create an organization and add creator as owner to that organization 
- [ ] Can add people to the organization 
- [ ] Organizations controller POST /organizations
- [ ] Create Organization Use Case
- [ ] Create Organization DTO

| Property Name | Property Type | Rules | 
| - | - | - |
| User ID | string | required, uuid, user exists | 
| Organization Name | string | required | 
| Logo | file | required, image mimetype | 

### Test Cases 

- [ ] User that creates the organization is added to the organization on create organization create
- [ ] User must exist
