### ISSUE TITLE
Portfolio and property permissions

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#19]
### Tasks 

- [x] Properties are added to portfolios
- [x] Portfolios belong to a user 
- [x] Users can have multiple portfolios

### Test Cases

- [x] When a user is created, a portfolio is also created for them (they have owner permission)
