### ISSUE TITLE
Create open house/viewing use case 

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#21]
### Tasks 

- [ ] Controller 
- [ ] DTO: user id, property listing id, start datetime, end datetime, duration of viewing (5, 10, 15, 20, 30), allow overlaps

### Test Cases

- [ ] user has permission to schedule open house 
- [ ] property exists 
- [ ] start is before end
