### ISSUE TITLE
Schedule viewing slot at open house use case

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#22]
### Tasks 

- [ ] DTO: guest email, open house id, date time slot, message
- [ ] Controller endpoint 
- [ ] Send email to guest confirming viewing (with address) if auto accept is enabled and notify manager that viewing has been scheduled
- [ ] Send email to guest with acknowledgement and notify manager that viewing needs to be accepted or denied 

### Test cases

- [ ] Open house exists and is accepting viewings
- [ ] Viewing slot is available 
- [ ] Email exists and is valid
