### ISSUE TITLE
Setup e2e testing infrastructure 

### ISSUE THREAD

**Issue by vincent-h-lee** [vincent-h-lee/property-management#26]
**Tasks**

- [ ] database changes persisted in tests  
- [ ] DATABASE_CONNECTION provider should be dynamically instantiated so we can insert different ORM configurations: testing, production, dev, etc 
- [ ] use a sqlite test database
